name: 3DS Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install devkitPro
        run: |
          sudo apt-get update
          sudo apt-get install -y devkitpro-pacman

      - name: Install 3DS tools
        run: |
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm 3ds-dev

      - name: Build
        run: |
          export DEVKITPRO=/opt/devkitpro

          arm-none-eabi-g++ \
            -I$DEVKITPRO/libctru/include \
            -O2 -std=c++17 \
            source/*.cpp \
            -L$DEVKITPRO/libctru/lib \
            -lctru -o Katto3DS.elf

      - uses: actions/upload-artifact@v4
        with:
          name: Katto3DS
          path: Katto3DS.elf
